### ISSUE TITLE
몇가지 의문점 및 건의

### ISSUE THREAD

**Issue by goddes4** [kr-zephyr/SpringBootWebAppSample#1]
- spring-boot-starter-data-jpa 는 왜 의존성 걸려 있는거야?
- mybatis 를 ibatis 개발 방식처럼 쓰고 있는거 같아.  
  namespace 를 mapper 패키지랑 동일하게 쓰면 스트링 형태로 뽑아 오지 않고, 
  인터페이스를 직접 @Autowired 해서 쓰면 되는데  특별한 이유라도? 
  http://www.nextree.co.kr/p3052/
- RestTemplate 쓰는게 더 편하지 않나?
- embedded tomcat port 나 InternalResourceViewResolver 설정을 application.properties 로 빼는게 좋은것 같아?

**Comment by kr-zephyr** [comment]
- spring-boot-starter-data-jpa는 지금보니 왜 들어갔는지 모르겠네...ㅎㅎ 아마도 이것저것 넣고 빼고 하다가 남은 것 같음.
- 사내에서 쓰려고 먼저 작업한 걸 변경한 소스인데, 아직 사내에서는 iBatis가 더 손에 익어있는 상태라서 iBatis의 향기가 남아 있음. 우발적으로 작업한 소스인지라 많이 손을 봐야 함.
- 사실 원래 목적은 완전한 REST 통신 지원은 아니었고, myBatis 정도만 붙이는 것이었는데 급하게 이렇게 저렇게 추가하다 보니 소스가 엉망;;;;
- 향후 properties는 좀 더 정리할 예정.

**Comment by sehaeng** [comment]
저도 남들보시라고 페메로 질문드렸던거 남길게요.
- BasicDataSource 를 굳이 쓰실필요가 없어보여요~(기본 톰캣CP쓰는게어떠실지)
- mybatis설정을 javaconfig로 바꾸면 xml 하나더 줄일수 있을듯해요.
